apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::640083577458:role/eksctl-roboshop-nodegroup-workers-NodeInstanceRole-OrtnEgXRUkGY
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
       - roboshop-trainee
      userarn: arn:aws:iam::640083577458:user/suresh
      username: suresh
    - groups:
       - roboshop-trainee
      userarn: arn:aws:iam::640083577458:user/john
      username: john
    - groups:
      -  roboshop-trainee
      userarn: arn:aws:iam::640083577458:user/rahim
      username: rahim
    - groups:
       - roboshop-admin
      userarn: arn:aws:iam::640083577458:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-26T08:30:09Z"
  name: aws-auth
  namespace: kube-system
  uid: 5d87b0a0-519b-4c94-8809-6d897f643403

